#!/bin/sh

# Redirect output to stderr.
exec 1>&2
# Run test before each commit.
git pull
cd your-race
exec mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=es.codeurjc.mastercloudapps:your-race
exec mvn test -Dtest=es.codeurjc.mastercloudapps.your_race.**

