{
 "title": "Analisis",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "process_cpu_usage all pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time(process_cpu_usage{application=\"\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{}[5m]) * 1000) by (instance)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{status=~\"^2\\\\d+$\"}[1m])) by (method,uri,outcome,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max ERROR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{status!~\"^2\\\\d+$\"}[1m])) by (method,uri,outcome,status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}