{
 "title": "Your-Race-Performance-Analysis",
 "tags": [ "your-race" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "process_cpu_usage all pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(process_cpu_usage{application=\"\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{}[5m]) * 1000) by (instance)",
     "legendFormat": "CPU Time {{instance}}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_sum- your race-All",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{app=\"your-race\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_sum- your race - KO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status, exception) (http_server_requests_seconds_max{app=\"your-race\", status!=\"201\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_sum- your race- OK - 201",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status,exception) (http_server_requests_seconds_max{app=\"your-race\",status=\"201\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Your Race", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "http_server_requests_seconds_max- your race- All - by status",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(status) (http_server_requests_seconds_max{app=\"your-race\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max- your race- Error 400",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "sum by(status, exception) (http_server_requests_seconds_max{app=\"your-race\", status=~\"400\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max- your race- Error 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 21 },
   "targets": [
    {
     "expr": "sum by(status, exception) (http_server_requests_seconds_max{app=\"your-race\", status=~\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max- your race- OK (201)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 17, "y": 29 },
   "targets": [
    {
     "expr": "sum by(status, exception) (http_server_requests_seconds_max{app=\"your-race\", status=\"201\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{status=~\"^2\\\\d+$\"}[1m])) by (method,uri,outcome,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max ERROR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{status!~\"^2\\\\d+$\"}[1m])) by (method,uri,outcome,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{ state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } }
 ]
}