@startuml
title Your Race - Domain Model

class YourRace
class Athlete
class Organizer
class Race
class Track
class Distance
class Date
class Location
class Consult
class Manage
class Apply
class Score
class PaymentInfo
class Dorsal
class ApplicationPeriod
class TrackRecord
class Suscription
class Registration

YourRace *--> Athlete
YourRace *--> Organizer

Organizer --> Manage

Athlete ..> Apply
Athlete --> Consult
Athlete *--> TrackRecord

Apply *--> ApplicationCode

Apply ..> Race

Consult --> Race

Manage --> Race


Race *--> Distance
Race *--> AthleteCapacity
Race *--> Date
Race *--> Location
Race *--> Type
Race *--> ApplicationPeriod
Race *--> Registration



Track -right-> Race 
Track -right-> Athlete 
Track *--> AthleteRegistrationDate
Track *--> Dorsal
Track *--> PaymentInfo
Track *--> Score

Registration *--> RegistrationType
Registration *--> RegistrationDate
Registration *--> RegistrationCost
Registration *--> ConcurrentRequestThreshold

RegistrationType <|-- ByDrawing
RegistrationType <|-- ByOrder


Organizer --> Suscription



@enduml