@startuml
title Your Race - Domain Model

class YourRace
class Athlete
class Organizer
class Race
class Track
class Distance
class Date
class Location
class Consult
class Manage
class Apply
class Score
class PaymentInfo
class Dorsal
class ApplicationPeriod
class TrackRecord
class Suscription
class RegistrationInfo

YourRace *--> Athlete
YourRace *--> Organizer

Organizer --> Manage

Athlete ..> Apply
Athlete --> Consult
Athlete *--> TrackRecord

Apply *--> ApplicationCode

Apply ..> Race

Consult --> Race

Manage --> Race


Race *--> Distance
Race *--> AthleteCapacity
Race *--> Date
Race *--> Location
Race *--> Score
Race *--> Type
Race *--> ApplicationPeriod
Race *--> RegistrationInfo



Track -right-> Race 
Track -right-> Athlete 
Track *--> RegistrationDate_
Track *--> Dorsal
Track *--> PaymentInfo
Track *--> Score_

RegistrationInfo *--> RegistrationType
RegistrationInfo *--> RegistrationDate
RegistrationInfo *--> RegistrationCost

RegistrationType <|-- ByDrawing
RegistrationType <|-- ByOrder


Organizer --> Suscription


@enduml